name: Push react-formal to main

on:
    push:
        tags:
            - 'v*'

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from develop
              uses: actions/checkout@v3
              with:
                  ref: develop

            - name: Debugging after checkout
              run: |
                  pwd
                  ls -la

            - name: Copy react-formal folder
              run: |
                  cp -r react-formal/ react-formal-tmp/

            - name: Checkout main branch
              run: |
                  git fetch origin main:main
                  git checkout main

            - name: Move copied folder into main
              run: |
                  mv react-formal-tmp/* ./

            - name: Commit and push to main
              run: |
                  git add .
                  git commit -m "Sync react-formal from develop"
                  git push origin main
