name: Push react-formol to main

on:
    push:
        tags:
            - 'v*'

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            # Checkout code from the develop branch
            - name: Checkout code from develop
              uses: actions/checkout@v2
              with:
                  ref: develop

            # Debugging step to display the current directory
            - name: Afficher le répertoire courant
              run: pwd

            # Debugging step to list all files and directories
            - name: Lister les fichiers
              run: ls -la

            # Copy react-formal folder
            - name: Copie du dossier react-formol
              run:
                  cp -r react-formol/ react-formol-tmp/ || echo "Échec de la
                  copie du dossier react-formol/"

            # Fetch and checkout main branch
            - name: Checkout main branch
              run: |
                  git fetch origin main:main
                  git checkout main

            # Move the copied folder to the current directory (inside main branch)
            - name: Move copied folder into main
              run: mv react-formol-tmp/* ./

            # Commit and push changes to main
            - name: Commit and push to main
              run: |
                  git add .
                  git commit -m "Sync react-formal from develop"
                  git push origin main
