name: Sync react-formol folder to main branch

on:
    push:
        branches:
            - develop

jobs:
    sync-folder:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from develop branch
              uses: actions/checkout@v3
              with:
                  ref: develop

            - name: Configure Git identity
              run: set-git-identity.sh

            # Switch to main branch
            - name: Checkout main branch
              run: |
                  git fetch origin main
                  git checkout main

            # Copy folder from develop to main branch
            - name: Copy react-formol folder
              run: |
                  git checkout develop -- react-formol/

            # Commit changes to main branch
            - name: Commit and push to main branch
              run: |
                  git add react-formol/
                  git commit -m "Sync react-formol folder from develop to main"
                  git push origin main
