name: Push react-formal to main

on:
    push:
        tags:
            - 'v*'

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code from develop
              uses: actions/checkout@v2
              with:
                  ref: develop

            # Étapes de débogage
            - name: Afficher le répertoire courant
              run: pwd

            - name: Lister les fichiers
              run: ls -la

            # Exécuter le script pour configurer l'identité Git
            - name: Set Git Identity
              run: ./set-git-identity.sh

            # Checkout sur la branche main
            - name: Checkout main branch
              run: |
                  git fetch origin main:main
                  git checkout main

            # Nouvelle étape de débogage avant la copie
            - name: Lister les fichiers avant la copie
              run: ls -la

            # Copier le dossier
            - name: Copy react-formal folder
              run: |
                  cp -r react-formal/ ../react-formal-tmp/ || echo "Erreur lors de la copie du dossier react-formal."

            # Nouvelle étape de débogage après la copie
            - name: Lister les fichiers après la copie
              run: ls -la ../

            # Commit et push sur la branche main
            - name: Commit and push to main
              run: |
                  git add ../react-formal-tmp/
                  git commit -m "Sync react-formal from develop"
                  git push origin main
