name: Push react-formol to main

on:
    push:
        branches:
            - develop # Trigger the workflow on push events to develop branch
        tags:
            - 'v*' # or when a tag starting with 'v' is created

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code from develop
              uses: actions/checkout@v2
              with:
                  ref: develop

            - name: Set Git Identity
              run: |
                  git config --global user.email "mahfod.dev@gmail.com"
                  git config --global user.name "Mahfod-dev"

            - name: Checkout main branch and remove similar folder
              run: |
                  git fetch origin main:main
                  git checkout main
                  git rm -rf react-formol/
                  git commit -m "Remove old react-formol folder"

            - name: Checkout react-formal folder from develop
              run: git checkout develop -- react-formal/

            - name: Rename react-formal to react-formol
              run: mv react-formal/ react-formol/

            - name: Commit and push to main
              run: |
                  git add react-formol/
                  git commit -m "Sync react-formal to react-formol in main"
                  git push origin main
